CREATE TABLE RATER(
USER_ID CHAR(6) PRIMARY KEY,
EMAIL CHAR(20),
NAME CHAR(15),
JOIN_DATE DATE,
RATER_TYPE CHAR(2),
REP DECIMAL(1,0)
);

CREATE TABLE RATING(
USER_ID CHAR(6) FOREIGN KEY,
RATE_DATE DATE,
PRICE DECIMAL(1,0),
FOOD DECIMAL(1,0),
MOOD DECIMAL (1,0),
STAFF DECIMAL (1,0).
COMMENTS CHAR(280),
RESTAURANT_ID CHAR(6) FOREIGN KEY,
PRIMARY KEY(USER_ID,RATE_DATE)
);

CREATE TABLE RESTAURANT(
RESTAURANT_ID CHAR(6) PRIMARY KEY,
NAME CHAR(15),
RES_TYPE CHAR(20),
URL CHAR(40)
);

CREATE TABLE LOCATION(
LOCATION_ID PRIMARY KEY,
FIRST_OPENED DATE,
MANAGER CHAR(20),
PHONE_NO CHAR(10),
ADDRESS CHAR(20),
HOUR_OPEN CHAR(5),
HOUR_CLOSE CHAR(5),
RESTAURANT_ID CHAR(6) FOREIGN KEY
);

CREATE TABLE MENU_ITEM(
ITEM_ID CHAR(6) PRIMARY KEY,
NAME CHAR(20),
TYPE CHAR(1),
CATEGORY CHAR(1),
DESCRIPTION CHAR(280),
PRICE DECIMAL (3,2),
RESTAURANT_ID CHAR(6) FOREIGN KEY
);

CREATE TABLE RATING_ITEM(
USER_ID CHAR(6),
RATE_DATE DATE,
ITEM_ID CHAR(6),
RATING DECIMAL(1,0),
COMMENT CHAR(280),
PRIMARY KEY (USER_ID, RATE_DATE, ITEM_ID)
);

