
--a
SELECT * FROM RESTAURANT WHERE NAME= <User_input>;

--b
SELECT NAME, CATEGORY, DESCRIPTION, PRICE FROM MENU_ITEM GROUP BY ITEM_ID HAVING RESTAURANT_ID = (SELECT RESTAURANT_ID FROM RESTAURANT WHERE NAME = <User_input>) ORDER BY CATEGORY;

--c
SELECT MANAGER, FIRST_OPENED FROM LOCATION GROUP BY MANAGER, FIRST_OPENED, RESTAURANT_ID HAVING RESTAURANT_ID IN (SELECT RESTAURANT_ID FROM RESTAURANT WHERE RES_TYPE = <User_input>);

--d
SELECT M.NAME, M.PRICE, L.MANAGER, L.HOUR_OPEN, L.HOUR_CLOSE, R.URL 
	FROM MENU_ITEM M, LOCATION L, RESTAURANT R 
    WHERE R.RESTAURANT_ID = L.RESTAURANT_ID 
		AND R.RESTAURANT_ID = M.RESTAURANT_ID 
		AND R.RESTAURANT_ID = (SELECT RESTAURANT_ID FROM RESTAURANT WHERE NAME=<User_input>)
		AND M.PRICE = (SELECT MAX(PRICE) FROM MENU_ITEM M, RESTAURANT R
		WHERE R.RESTAURANT_ID = M.RESTAURANT_ID 
		AND R.RESTAURANT_ID = (SELECT RESTAURANT_ID FROM RESTAURANT WHERE NAME=<User_input>))
	GROUP BY M.NAME, M.PRICE, L.MANAGER, L.HOUR_OPEN, L.HOUR_CLOSE, R.URL

--e	
SELECT R.RES_TYPE, M.CATEGORY, AVG(M.PRICE) 
	FROM MENU_ITEM M, RESTAURANT R
	WHERE R.restaurant_id = M.restaurant_id
	GROUP BY R.RES_TYPE, M.CATEGORY ORDER BY R.RES_TYPE, M.CATEGORY;
	

--f 
SELECT RATER.NAME, RESTAURANT.NAME, COUNT(RATING.*) AS ratings FROM (RATER INNER JOIN RATING ON RATER.USER_ID=RATING.USER_ID) INNER JOIN RESTAURANT ON RATING.RESTAURANT_ID=RESTAURANT.RESTAURANT_ID
GROUP BY RATER.NAME, RESTAURANT.NAME ORDER BY RATER.NAME
  
--g
SELECT R.NAME, L.PHONE_NO FROM LOCATION L, RESTAURANT R
  WHERE (SELECT COUNT(RATE_DATE) FROM RATING WHERE RESTAURANT_ID=R.RESTAURANT_ID AND RATE_DATE >= '2015-01-01' AND RATE_DATE <= '2015-01-31') = 0
  AND L.RESTAURANT_ID=R.RESTAURANT_ID
  GROUP BY R.NAME, L.PHONE_NO ORDER BY R.NAME

--h
SELECT R.NAME, L.FIRST_OPENED FROM RESTAURANT R, LOCATION L WHERE
  R.RESTAURANT_ID IN (SELECT RESTAURANT_ID FROM RATING WHERE R.RESTAURANT_ID=RESTAURANT_ID 
					AND STAFF < (SELECT MIN(STAFF) FROM RATING WHERE USER_ID='100002')
					AND STAFF < (SELECT MIN(FOOD) FROM RATING WHERE USER_ID='100002')
					AND STAFF < (SELECT MIN(MOOD) FROM RATING WHERE USER_ID='100002')
					AND STAFF < (SELECT MIN(PRICE) FROM RATING WHERE USER_ID='100002')) 
  AND R.RESTAURANT_ID = L.RESTAURANT_ID;
  
--i
SELECT RESTAURANT.NAME, RATER.NAME FROM (RESTAURANT INNER JOIN RATING ON RESTAURANT.RESTAURANT_ID=RATING.RESTAURANT_ID) INNER JOIN RATER ON RATING.USER_ID=RATER.USER_ID
	WHERE FOOD = (SELECT MAX(FOOD) FROM RATING)
	AND RES_TYPE='Canadian'
	GROUP BY RATER.NAME, RESTAURANT.NAME ORDER BY RATER.NAME

--j
SELECT RES_TYPE FROM RESTAURANT GROUP BY RES_TYPE,RESTAURANT_ID ORDER BY (SELECT SUM(FOOD+MOOD+STAFF+PRICE) FROM RATING WHERE RATING.RESTAURANT_ID=RESTAURANT.RESTAURANT_ID)

--k
SELECT RATER.NAME, RATER.JOIN_DATE, RATER.REP, RESTAURANT.NAME, RATING.RATE_DATE
	FROM RATER INNER JOIN RATING ON RATER.USER_ID=RATING.USER_ID INNER JOIN RESTAURANT ON RESTAURANT.RESTAURANT_ID=RATING.RESTAURANT_ID
	WHERE FOOD+MOOD = (SELECT MAX(FOOD+MOOD) FROM RATING)

--l
SELECT RATER.NAME, RATER.JOIN_DATE, RATER.REP, RESTAURANT.NAME, RATING.RATE_DATE
	FROM RATER INNER JOIN RATING ON RATER.USER_ID=RATING.USER_ID INNER JOIN RESTAURANT ON RESTAURANT.RESTAURANT_ID=RATING.RESTAURANT_ID
	WHERE FOOD = (SELECT MAX(FOOD) FROM RATING)
		OR MOOD = (SELECT MAX(MOOD) FROM RATING)
  
--m 
WITH COUNTER(COUNTER1, COUNTER_ID) AS (SELECT COUNT(*), USER_ID FROM RATING WHERE RESTAURANT_ID=(SELECT RESTAURANT_ID FROM RESTAURANT WHERE NAME='Salt') GROUP BY USER_ID),
MAXER (MAX_COUNT) AS (SELECT MAX(COUNTER1) FROM COUNTER)
SELECT RATER.NAME, RATER.REP, RESTAURANT.NAME, COUNTER1 
	FROM RATER INNER JOIN RATING ON RATER.USER_ID=RATING.USER_ID INNER JOIN RESTAURANT ON RESTAURANT.RESTAURANT_ID=RATING.RESTAURANT_ID, COUNTER
	WHERE RESTAURANT.NAME='Salt'
	AND (SELECT COUNTER1 FROM COUNTER WHERE COUNTER_ID=RATER.USER_ID)=(SELECT MAX_COUNT FROM MAXER)
	GROUP BY RATER.NAME, RATER.REP, RESTAURANT.NAME, COUNTER1
	
--n 
SELECT NAME, EMAIL FROM RATER INNER JOIN RATING ON RATING.USER_ID=RATER.USER_ID 
WHERE PRICE+MOOD+FOOD+STAFF < (SELECT MIN(PRICE+MOOD+FOOD+STAFF) FROM RATING WHERE USER_ID IN (SELECT USER_ID FROM RATER WHERE NAME='John'))
GROUP BY RATER.USER_ID
	
--o 
WITH RATERS (ALL_COUNT,ALL_USER_ID) AS (
				SELECT COUNT(*), RATING.USER_ID
				FROM RATER, RATING
				WHERE RATER.USER_ID = RATING.USER_ID
				GROUP BY RATING.USER_ID 

			),  MAXIMUM (MAX_COUNT)AS (
				SELECT MAX(ALL_COUNT)
				FROM RATERS

			),MAX_USER_ID (USER_ID) AS (
					SELECT ALL_USER_ID 
					FROM MAXIMUM, RATERS
					WHERE MAXIMUM.MAX_COUNT = RATERS.ALL_COUNT
			)

			SELECT RATER.NAME,RATER.RATER_TYPE, RATER.EMAIL
			FROM RATER, MAX_USER_ID
			WHERE RATER.USER_ID = MAX_USER_ID.USER_ID






